language: node_js
jobs:
  include:
    - stage: test
      node_js: 8
      script:
        - yarn test
        - yarn build
    - node_js: 10
      script:
        - yarn test
        - yarn build
    - node_js: 12
      script:
        - yarn lint
        - yarn test
        - yarn build
      after_success: yarn coveralls
